from pathlib import Path

from app.media.profiles import EncodingProfile, scale_filter
from app.schemas.edl import TrimOp


def build_segment_args(
    src: Path, op: TrimOp, dst: Path, profile: EncodingProfile, has_audio: bool
) -> list[str]:
    # Re-encoding (not stream copy) makes cuts frame-accurate instead of snapping to keyframes. Every
    # segment shares the profile and a fixed audio layout, which is what lets the concat step stream-copy.
    audio = [*profile.audio_args, "-ar", "48000", "-ac", "2"] if has_audio else ["-an"]
    return [
        "-ss", f"{op.start:.3f}",
        "-i", str(src),
        "-t", f"{op.end - op.start:.3f}",
        "-vf", scale_filter(profile.max_height),
        *profile.video_args,
        *audio,
        "-movflags", "+faststart",
        str(dst),
    ]  # fmt: skip


def concat_list(segments: list[Path]) -> str:
    # Paths are generated by Storage (uuid-based, validated segments), so they never contain quotes.
    return "".join(f"file '{p}'\n" for p in segments)


def build_concat_args(list_file: Path, dst: Path) -> list[str]:
    return [
        "-f",
        "concat",
        "-safe",
        "0",
        "-i",
        str(list_file),
        "-c",
        "copy",
        "-movflags",
        "+faststart",
        str(dst),
    ]
